services:
  redis:
    image: redis:8.2.0-alpine
    container_name: go-weather-api-proxy-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--save", "60 1", "--loglevel", "warning"]
    volumes:
      - go-weather-api-proxy-redis-data:/data

volumes:
  go-weather-api-proxy-redis-data: